In [1]:
import pandas as pd
import numpy as np

X = np.random.randint(10,50,100).reshape(20,5)
X

C:\Users\abhin\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


array([[19, 21, 27, 41, 25],
       [21, 33, 22, 29, 42],
       [24, 20, 48, 32, 26],
       [23, 19, 32, 40, 26],
       [11, 22, 47, 21, 16],
       [13, 18, 25, 48, 44],
       [19, 11, 17, 36, 23],
       [14, 19, 22, 22, 38],
       [10, 26, 12, 17, 38],
       [18, 14, 29, 35, 38],
       [19, 20, 27, 33, 38],
       [33, 15, 25, 33, 43],
       [37, 34, 19, 45, 20],
       [16, 24, 11, 25, 41],
       [13, 41, 14, 36, 22],
       [29, 15, 42, 37, 12],
       [41, 36, 37, 17, 29],
       [32, 11, 17, 49, 21],
       [18, 32, 16, 17, 43],
       [42, 27, 12, 31, 48]])

In [2]:
X_meaned = X - np.mean(X, axis = 0)

In [3]:
X_meaned

array([[ -3.6 ,  -1.9 ,   1.95,   8.8 ,  -6.65],
       [ -1.6 ,  10.1 ,  -3.05,  -3.2 ,  10.35],
       [  1.4 ,  -2.9 ,  22.95,  -0.2 ,  -5.65],
       [  0.4 ,  -3.9 ,   6.95,   7.8 ,  -5.65],
       [-11.6 ,  -0.9 ,  21.95, -11.2 , -15.65],
       [ -9.6 ,  -4.9 ,  -0.05,  15.8 ,  12.35],
       [ -3.6 , -11.9 ,  -8.05,   3.8 ,  -8.65],
       [ -8.6 ,  -3.9 ,  -3.05, -10.2 ,   6.35],
       [-12.6 ,   3.1 , -13.05, -15.2 ,   6.35],
       [ -4.6 ,  -8.9 ,   3.95,   2.8 ,   6.35],
       [ -3.6 ,  -2.9 ,   1.95,   0.8 ,   6.35],
       [ 10.4 ,  -7.9 ,  -0.05,   0.8 ,  11.35],
       [ 14.4 ,  11.1 ,  -6.05,  12.8 , -11.65],
       [ -6.6 ,   1.1 , -14.05,  -7.2 ,   9.35],
       [ -9.6 ,  18.1 , -11.05,   3.8 ,  -9.65],
       [  6.4 ,  -7.9 ,  16.95,   4.8 , -19.65],
       [ 18.4 ,  13.1 ,  11.95, -15.2 ,  -2.65],
       [  9.4 , -11.9 ,  -8.05,  16.8 , -10.65],
       [ -4.6 ,   9.1 ,  -9.05, -15.2 ,  11.35],
       [ 19.4 ,   4.1 , -13.05,  -1.2 ,  16.35]])

In [4]:
cov_mat = np.cov(X_meaned,rowvar = False)
cov_mat

array([[ 96.88421053,   7.58947368,   6.6       ,  19.13684211,
         -6.51578947],
       [  7.58947368,  73.56842105, -22.15263158, -32.08421053,
          8.75263158],
       [  6.6       , -22.15263158, 128.26052632,  -3.11578947,
        -58.03421053],
       [ 19.13684211, -32.08421053,  -3.11578947,  99.01052632,
        -31.82105263],
       [ -6.51578947,   8.75263158, -58.03421053, -31.82105263,
        115.60789474]])

In [5]:
eigen_values, eigen_vectors = np.linalg.eigh(cov_mat)
print(eigen_values)
print(eigen_vectors)

[ 30.95780264  71.893751    96.86824939 119.8949225  193.71685341]
[[ 0.22382128  0.28579486  0.82970873 -0.40412762 -0.12841193]
 [-0.57464132 -0.57004729  0.49219239  0.21316898  0.23903782]
 [-0.40431014  0.40801893  0.10513149  0.48687337 -0.64958106]
 [-0.54128894 -0.06655522 -0.24023588 -0.7442437  -0.30160358]
 [-0.40401855  0.64996795 -0.02375216 -0.01718986  0.64300157]]


In [8]:
sorted_index = np.argsort(eigen_values)[::-1]
sorted_eigenVecotors = eigen_vectors[:,sorted_index]

In [9]:
n_comp = 2
eigen_vectors_subset = sorted_eigenVecotors[:,0:n_comp]

In [10]:
X_reuced = np.dot(eigen_vectors_subset.transpose(),X.transpose()).transpose()